export { default as Home} from './Home'
export { default as ProductDetails} from  './ProductDetails'
export {default as LogIn} from './LogIn'
export {default as Purchases} from './Purchases'
export {default as ProtectedRoutes} from './ProtectedRoutes'

export { default as AboutUs} from './AboutUs'
export { default as Blog} from  './Blog'
export {default as Contact} from './Contact'
export {default as Experience} from './Experience'
export {default as Services} from './Services'
